# Generated by Django 3.2.6 on 2021-08-24 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
